### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by tccxy** [ikwzm/xf86-video-armsoc-xilinx#1]
hi
   i clone this rep in my pc,
   when i build
   the console show as flow
```
root@debian:/home/zw/xf86-video-armsoc-xilinx# ./debian/rules binary
dh binary --with quilt,autoreconf,xsf --builddirectory=build/
dh: No packages to build. Architecture mismatch: amd64, want: armhf arm64
```

  i just do as flow
```
shell$ ./autogen.sh
shell$ make distclean
shell$ sudo debian/rules binary
```

  thanks a lot

**Comment by ikwzm** [comment]
Thank you for the issue.

I'm sorry, but I don't know because I haven't had any experience building on cross-compilation on a PC.

Debian packages are self-built in a Linux development environment running on ZynqMP.
The Linux development environment that runs on ZynqMP uses one of the following:

https://github.com/ikwzm/ZynqMP-FPGA-Linux
https://github.com/ikwzm/ZynqMP-FPGA-Ubuntu18.04-Ultra96

**Comment by tccxy** [comment]
Thanks a lot
&nbsp; I did the same thing with qemu's virtual arm and it worked
&nbsp; I dpkg this deb in ultra96-v2,use my own ubuntu16.04 file system
&nbsp; The serial console prompt fllow

I'm sure kernel and driver are correct


en....
Do you have any Suggestions, thanks a lot







&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"KAWAZOME Ichiro"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月13日(星期三) 下午3:45
收件人:&nbsp;"ikwzm/xf86-video-armsoc-xilinx"<xf86-video-armsoc-xilinx@noreply.github.com&gt;;
抄送:&nbsp;"肥肠驴行"<13110030616@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [ikwzm/xf86-video-armsoc-xilinx] build error (#1)





 
Thank you for the issue.
 
I'm sorry, but I don't know because I haven't had any experience building on cross-compilation on a PC.
 
Debian packages are self-built in a Linux development environment running on ZynqMP.
 The Linux development environment that runs on ZynqMP uses one of the following:
 
https://github.com/ikwzm/ZynqMP-FPGA-Linux
 https://github.com/ikwzm/ZynqMP-FPGA-Ubuntu18.04-Ultra96

**Comment by tccxy** [comment]
> 
> 
> Thank you for the issue.
> 
> I'm sorry, but I don't know because I haven't had any experience building on cross-compilation on a PC.
> 
> Debian packages are self-built in a Linux development environment running on ZynqMP.
> The Linux development environment that runs on ZynqMP uses one of the following:
> 
> https://github.com/ikwzm/ZynqMP-FPGA-Linux
> https://github.com/ikwzm/ZynqMP-FPGA-Ubuntu18.04-Ultra96

Thanks a lot
  I did the same thing with qemu's virtual arm and it worked
  I dpkg this deb in ultra96-v2,use my own ubuntu16.04 file system
  The serial console prompt fllow
```
root@localhost:/home/autobrain# xinit 


X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-131-generic aarch64 Ubuntu
Current Operating System: Linux localhost.localdomain 4.19.0 #1 SMP Mon May 11 23:54:02 UTC 2020 aarch64
Kernel command line: earlycon console=ttyPS0,115200 clk_ignore_unused root=/dev/mmcblk0p2 rw rootwait
Build Date: 10 August 2018  12:01:21PM
xorg-server 2:1.18.4-0ubuntu0.8 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Tue May 12 10:05:05 2020
(==) Using config file: "/etc/X11/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 0
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
xinit: giving up
xinit: unable to connect to X server: Connection refused
xinit: server error
root@localhost:/home/autobrain# lsmod 
Module                  Size  Used by
mali                  253952  0
zynqmp_r5_remoteproc    20480  0
uio_pdrv_genirq        16384  0
root@localhost:/home/autobrain# 
```
I'm sure kernel and driver are correct

en....
Do you have any Suggestions, thanks a lot
